version: '2'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app/backend
  frontend:
    image: osrm/osrm-frontend:latest
    ports:
      - "9966:9966"
    links:
      - backend
    depends_on:
      - backend
